apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzuwebapp
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=tanzuwebapp"
spec:
  type: application
  lifecycle: experimental
  owner: default-team
